Task24_Low/Models/Article.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task24_Low.Models
{
    public class Article
    {
        public string Name { get; set; }
        public DateTime Date { get; set; }
        public string Text { get; set; }
    }
}

Task24_Low/Models/FormData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task24_Low.Models
{
    public class FormData
    {
        public string Visit { get; set; }
        public string Satisfaction { get; set; }
        public string PrimaryUsing { get; set; }
        public string LevelOfService { get; set; }
    }
}

Task24_Low/Models/Review.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task24_Low.Models
{
    public class Review
    {
        public string AuthorName { get; set; }
        public DateTime Date { get; set; }
        public string Text { get; set; }
    }
}

Task24_Low/Controllers/FormController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task24_Low.Models;

namespace Task24_Low.Controllers
{
    public class FormController : Controller
    {
        [HttpGet]
        public ActionResult Form()
        {
            return View("FormPage");
        }

        [HttpPost]
        public ActionResult FormPage(FormData data)
        {
            if (String.IsNullOrEmpty(data.LevelOfService))
                ModelState.AddModelError("LevelOfService", "Please choise a level of service");
            
            if (String.IsNullOrEmpty(data.PrimaryUsing))
                ModelState.AddModelError("PrimaryUsing", "Please tell about your primary using of this library");
            
            if (String.IsNullOrEmpty(data.Satisfaction))
                ModelState.AddModelError("Satisfaction", "Please choise your satisfaction level");
            
            if (String.IsNullOrEmpty(data.Visit))
                ModelState.AddModelError("Visit", "Please say how often do you visit library");
            
            if (ModelState.IsValid)
            {
                (HttpContext.Application["forms"] as List<FormData>)
                .Add(data);
                return RedirectToAction("FormPage");
            }
            else
                return View("FormPage");
            
        }

        [HttpGet]
        public ActionResult FormPage()
        {
            return View("FormPageResult", HttpContext.Application["forms"] );
        }
    }
}

Task24_Low/Controllers/GuestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Task24_Low.Models;

namespace Task23_Middle.Controllers
{
    public class GuestController : Controller
    {
        [HttpGet]
        public ActionResult GuestPage()
        {
            return View(HttpContext.Application["reviews"]);
        }

        [HttpPost]
        public ActionResult AddReview(Review review)
        {
            if (string.IsNullOrEmpty(review.AuthorName) && 
                    string.IsNullOrEmpty(review.Text))
            {
                ModelState.AddModelError(
                    "", "Please enter your name and your review");
            }
            else if (!string.IsNullOrEmpty(review.AuthorName) &&
                    string.IsNullOrEmpty(review.Text))
            {
                ModelState.AddModelError("", "Please enter your review");
            } 
            else if (string.IsNullOrEmpty(review.AuthorName) &&
                    !string.IsNullOrEmpty(review.Text))
            {
                ModelState.AddModelError("", "Please enter your name");
            }

            if (ModelState.IsValid)
            {
                (HttpContext.Application["reviews"] as List<Review>)
                    .Add(review);
                return new RedirectResult("/Guest/GuestPage");
            }
            else
            {
                return View("GuestPage", HttpContext.Application["reviews"]);
            }
        }
    }
}

Task24_Low/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task24_Low.Controllers
{
    public class MainController : Controller
    {
        public ActionResult MainPage()
        {
            return View(HttpContext.Application["articles"]);
        }
    }
}

Task24_Low/Views/Form/FormPage.cshtml
@model Task24_Low.Models.FormData
@{
    ViewBag.Title = "Form Page";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css"/>

<div id="form">
    @using (Html.BeginForm("FormPage", "Form", FormMethod.Post))
    {
        @Html.ValidationSummary(true)
    <div class="form-group">
        <h2 class="text-center">How ofter do you visit the library?</h2>
        @Html.ListBoxFor(m => m.Visit, new MultiSelectList(
                           new string[] { "Monthly", "Weekly", "Daily" }),
                           new { @class = "form-control" })
        <p class="alert-danger">@Html.ValidationMessageFor(m => m.Visit)</p>
    </div>
    <div class="form-group">
        <h2 class="text-center">
            How satisfied are you with the
            opening hours of the library?
        </h2>
        @Html.ListBoxFor(m => m.Satisfaction, new MultiSelectList(
                      new string[] {"Satisfied", "Indiffirent",
                    "Dissatisfied"}), new { @class = "form-control" })
        <p class="alert-danger">@Html.ValidationMessageFor(m => m.Satisfaction)</p>
    </div>
    <div class="form-group">
        <h2 class="text-center">
            Rate our services
        </h2>
        @Html.ListBoxFor(m => m.LevelOfService, new MultiSelectList(
                            new string[] {"Excelent", "Very good", "Sufficient",
                    "Insufficient"}), new { @class = "form-control" })
        <p class="alert-danger">@Html.ValidationMessageFor(m => m.LevelOfService)</p>
    </div>
    <div class="form-group">
        <h2 class="text-center">
            Why do you primarily use the library
            and its services?
        </h2>
        @Html.ListBoxFor(m => m.PrimaryUsing, new MultiSelectList(
                                 new string[] { "Leisure", "Education", "Work" }),
                                     new { @class = "form-control" })
        <p class="alert-danger">@Html.ValidationMessageFor(m => m.PrimaryUsing)</p>
    </div>
    <button type="submit" class="btn btn-primary form-control">Send</button>
    }
</div>

Task24_Low/Views/Form/FormPageResult.cshtml
@model List<Task24_Low.Models.FormData>
@using Task24_Low.ExtensionMethods

@{ 
    ViewBag.Title = "Result of form";
    Layout = "~/Views/Shared/_Layout.cshtml"; 
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

@Html.DrawResults(Model)

Task24_Low/Views/Guest/GuestPage.cshtml
@model List<Task24_Low.Models.Review>﻿
@{ 
    ViewBag.Title = "Guest Page";
    Layout = "~/Views/Shared/_Layout.cshtml"; 
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

<div id="reviews" class="col-md-offset-2">
    @foreach (var a in Model)
    {
    <div class="article">
        <p class="articleName">@a.AuthorName:</p>
        <p class="articleDate">@a.Date.ToShortDateString()</p>
        <p class="articleText">@a.Text</p>
    </div>
    }

    @using (Html.BeginForm("AddReview", "Guest", FormMethod.Post))
    {
        @Html.ValidationSummary(true)
        <input type="hidden" value=@DateTime.Now.ToShortDateString() name="Date" />
        <div class="form-group">
            <p>Enter your name</p>
            @Html.TextBox("AuthorName", "", new { @class="form-control" })
            @*<p class="alert-danger">@Html.ValidationMessage("AuthorName")</p>*@
        </div>
        <div class="form-group">
            <p>Enter your review</p>
            @Html.TextArea("Text", "", null)
            @*<p class="alert-danger">@Html.ValidationMessage("Text")</p>*@
        </div>
        <input type="submit" class="form-control btn-primary" value="Send" />
    }
</div>

Task24_Low/Views/Main/MainPage.cshtml
@model List<Task24_Low.Models.Article>
@{ 
    ViewBag.Title = "Main Page"; 
}

<link href="~/Content/Site.css" rel="stylesheet" type="text/css" />

@foreach (var a in Model)
{
<div>
    <h2>@a.Name</h2>
    <p>@a.Date.ToShortDateString()</p>
    <p>@a.Text</p>
</div>}

Task24_Low/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href=@Url.Content("~/Content/Site.css") type="text/css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <main>
        <h1 class="text-center">
            <img alt="logo" src="~/logo.png" class="logo" />
            Library "Task23_Middle"
        </h1>
    </main>
    <div id="content" class="row">
        <div id="left" class="col-md-8">
            @RenderBody()
        </div>
        <div id="menu" class="col-md-2">
            <ul class="nav nav-stacked nav-pills text-center">
                <li><a href="/Main/MainPage">Main page</a></li>
                <li><a href="/Guest/GuestPage">Guest page</a></li>
                <li><a href="/Form/Form">Form page</a></li>
            </ul>
        </div>
    </div>
    <br />
    <footer>
        <p class="text-center">
            Copyright &copy; @DateTime.Now.Year. All Rights Reserved.
            Maksym Kot
            <a href="#" class="text-center" id="up">To Top</a>
        </p>
        <script src="~/Scripts/up.js"></script>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>